services:
  - type: web
    name: angular-app
    env: static
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: dist/client
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
